language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt

script:
  - python -m unittest tests/test_app.py

before_script:
  - export FLASK_APP=main.py
  - psql -c 'create database database_testing;' -U postgres
  - export DATABASE_URL=postgresql://postgres@localhost/database_testing
  - flask init_db
