"""empty message

Revision ID: d8b627ee5ae0
Revises: f99acd036dc1
Create Date: 2018-03-16 17:24:53.027712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b627ee5ae0'
down_revision = 'f99acd036dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choice_of_user', sa.Column('poll_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'choice_of_user', 'poll', ['poll_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'choice_of_user', type_='foreignkey')
    op.drop_column('choice_of_user', 'poll_id')
    # ### end Alembic commands ###
